### ISSUE TITLE
Toilet Routing Issue

### ISSUE THREAD

**Issue by joncode21** [axoverse/xworld_amb#2] opened 2023-01-11 07:34 UTC
Navmeshes has a routing limit.

![Axoverse image 1](https://user-images.githubusercontent.com/75573916/211743424-033a1e25-7993-4eb1-8286-6cc6675f63e0.jpg)

  ##@seghcder

**Comment by seghcder** [comment] 2023-01-11 23:06
In the prefabs for the rooms, hide or open the door so there's enough room for the navmesh to be mapped into the area

![image](https://user-images.githubusercontent.com/28666447/211936395-e45b2f17-8bb1-4ab9-aa6d-2361afb7bbb3.png)

You can also get a patient to use a toilet in the room by getting their bed, then search upward in the gameobject hierarchy to get the room, then do a getComponentInChilden<RoutingWaypoint>() to get the toilet within the room, then set that as the destination.

If the issue is resolved pls close it :-)

**Closed** 2023-01-16 09:43 UTC
